# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.13.0-argon
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome-node-1:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
#  firefox-node1:
#    image: selenium/node-firefox:3.13.0-argon
#    depends_on:
#      - selenium-hub
#    environment:
#      - HUB_HOST=selenium-hub
#      - HUB_PORT=4444
  chrome-node-2:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome-node-3:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome-node-4:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  chrome-node-5:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444